#include "gmm_swift_bridge.h"

#include <catch2/catch_test_macros.hpp>

#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <unistd.h>

namespace fs = std::filesystem;

namespace {

std::string read_text(const fs::path& path) {
    std::ifstream input(path);
    return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
}

fs::path fixture_root() {
    const auto root = fs::temp_directory_path() /
                      ("gmm_swift_bridge_" + std::to_string(getpid()));
    fs::remove_all(root);
    fs::create_directories(root / "instances" / "Fixture" / "profiles" / "Default");
    fs::create_directories(root / "instances" / "Fixture" / "mods" / "Alpha" / "meshes");
    fs::create_directories(root / "instances" / "Fixture" / "mods" / "Beta" / "meshes");

    std::ofstream(root / "instances" / "Fixture" / "instance.toml")
        << "game_id = \"SkyrimSpecialEdition\"\n";
    std::ofstream(root / "instances" / "Fixture" / "profiles" / "Default" / "modlist.txt")
        << "+Beta\n-Alpha\n";
    return root;
}

}  // namespace

TEST_CASE("Swift bridge handles nulls, cancellation, and owned errors", "[macos][swiftui]") {
    auto* operation = gmm_swift_operation_create();
    REQUIRE(operation != nullptr);
    REQUIRE(gmm_swift_operation_is_cancelled(operation) == 0);
    gmm_swift_operation_cancel(operation);
    REQUIRE(gmm_swift_operation_is_cancelled(operation) == 1);
    REQUIRE(gmm_swift_snapshot_create(nullptr, "missing", operation) == nullptr);
    gmm_swift_operation_destroy(operation);

    REQUIRE(gmm_swift_instance_count(nullptr) == 0);
    REQUIRE(gmm_swift_instance_id(nullptr, 0) == nullptr);
    REQUIRE(gmm_swift_snapshot_instance_id(nullptr) == nullptr);
    REQUIRE(gmm_swift_snapshot_mod_count(nullptr) == 0);
    REQUIRE(gmm_swift_snapshot_mod_at(nullptr, 0).id == nullptr);
    REQUIRE(gmm_swift_last_error(nullptr) == nullptr);
    REQUIRE(gmm_swift_subscribe_refresh(nullptr, nullptr, nullptr) == 0);
    gmm_swift_engine_destroy(nullptr);
    gmm_swift_snapshot_destroy(nullptr);
    gmm_swift_operation_destroy(nullptr);

    auto* engine = gmm_swift_engine_create("/path/that/does/not/exist", nullptr);
    REQUIRE(engine != nullptr);
    REQUIRE(gmm_swift_snapshot_create(engine, "missing", nullptr) == nullptr);
    const char* error = gmm_swift_last_error(engine);
    REQUIRE(error != nullptr);
    REQUIRE(std::string(error).find("instance was not found") != std::string::npos);
    gmm_swift_free_string(error);
    gmm_swift_engine_destroy(engine);
}

TEST_CASE("Swift bridge scans and mutates a fixture", "[macos][swiftui]") {
    const auto root = fixture_root();
    const auto instance_toml = read_text(root / "instances" / "Fixture" / "instance.toml");
    const auto modlist = read_text(
        root / "instances" / "Fixture" / "profiles" / "Default" / "modlist.txt");
    auto* engine = gmm_swift_engine_create(
        (root / "instances").c_str(), GMM_SWIFT_TEST_PLUGINS_DIR);
    REQUIRE(engine != nullptr);
    REQUIRE(gmm_swift_instance_count(engine) == 1);
    REQUIRE(std::string(gmm_swift_instance_id(engine, 0)) == "Fixture");

    auto* snapshot = gmm_swift_snapshot_create(engine, "Fixture", nullptr);
    REQUIRE(snapshot != nullptr);
    REQUIRE(std::string(gmm_swift_snapshot_instance_id(snapshot)) == "Fixture");
    REQUIRE(std::string(gmm_swift_snapshot_game_id(snapshot)) == "SkyrimSpecialEdition");
    REQUIRE(std::string(gmm_swift_snapshot_profile_id(snapshot)) == "Default");
    REQUIRE(gmm_swift_snapshot_mod_count(snapshot) == 2);
    const auto first = gmm_swift_snapshot_mod_at(snapshot, 0);
    const auto second = gmm_swift_snapshot_mod_at(snapshot, 1);
    REQUIRE(std::string(first.id) == "Alpha");
    REQUIRE(first.order == 0);
    REQUIRE(first.enabled == 0);
    REQUIRE(std::string(second.id) == "Beta");
    REQUIRE(second.order == 1);
    REQUIRE(second.enabled == 1);
    gmm_swift_snapshot_destroy(snapshot);
    gmm_swift_engine_destroy(engine);
    REQUIRE(read_text(root / "instances" / "Fixture" / "instance.toml") == instance_toml);
    REQUIRE(read_text(root / "instances" / "Fixture" / "profiles" / "Default" / "modlist.txt") ==
            modlist);

    auto* mutation = gmm_swift_set_mod_enabled(
        engine, "Fixture", "Default", "Beta", 0, nullptr);
    REQUIRE(mutation != nullptr);
    REQUIRE(gmm_swift_result_code(mutation) == GMM_SWIFT_RESULT_OK);
    auto* updated = gmm_swift_result_snapshot(mutation);
    REQUIRE(updated != nullptr);
    REQUIRE(gmm_swift_snapshot_mod_at(updated, 1).enabled == 0);
    REQUIRE(read_text(root / "instances" / "Fixture" / "profiles" / "Default" / "modlist.txt") ==
            "# This file was automatically generated by GameModManager.\r\n"
            "-Beta\r\n"
            "-Alpha\r\n");
    gmm_swift_result_destroy(mutation);
    fs::remove_all(root);
}

TEST_CASE("Swift bridge reorders mods and reports not-found", "[macos][swiftui]") {
    const auto root = fixture_root();
    const auto modlist = root / "instances" / "Fixture" / "profiles" / "Default" / "modlist.txt";
    auto* engine = gmm_swift_engine_create(
        (root / "instances").c_str(), GMM_SWIFT_TEST_PLUGINS_DIR);
    REQUIRE(engine != nullptr);

    // Round-trip: move Beta (priority 1) to the top and verify snapshot + persistence.
    auto* mutation = gmm_swift_move_mod(engine, "Fixture", "Default", "Beta", 0, nullptr);
    REQUIRE(mutation != nullptr);
    REQUIRE(gmm_swift_result_code(mutation) == GMM_SWIFT_RESULT_OK);
    auto* updated = gmm_swift_result_snapshot(mutation);
    REQUIRE(updated != nullptr);
    REQUIRE(gmm_swift_snapshot_mod_count(updated) == 2);
    REQUIRE(std::string(gmm_swift_snapshot_mod_at(updated, 0).id) == "Beta");
    REQUIRE(gmm_swift_snapshot_mod_at(updated, 0).order == 0);
    REQUIRE(std::string(gmm_swift_snapshot_mod_at(updated, 1).id) == "Alpha");
    REQUIRE(gmm_swift_snapshot_mod_at(updated, 1).order == 1);
    // Snapshot is owned by the mutation result; gmm_swift_result_destroy frees it.
    gmm_swift_result_destroy(mutation);
    REQUIRE(read_text(modlist) ==
            "# This file was automatically generated by GameModManager.\r\n"
            "-Alpha\r\n"
            "+Beta\r\n");

    // Not-found failure: explicit error code, no data corruption.
    auto* missing = gmm_swift_move_mod(engine, "Fixture", "Default", "Missing", 0, nullptr);
    REQUIRE(missing != nullptr);
    REQUIRE(gmm_swift_result_code(missing) == GMM_SWIFT_RESULT_ERROR);
    const char* message = gmm_swift_result_error(missing);
    REQUIRE(message != nullptr);
    REQUIRE(std::string(message).find("mod was not found") != std::string::npos);
    gmm_swift_result_destroy(missing);
    REQUIRE(read_text(modlist) ==
            "# This file was automatically generated by GameModManager.\r\n"
            "-Alpha\r\n"
            "+Beta\r\n");

    gmm_swift_engine_destroy(engine);
    fs::remove_all(root);
}
