# packaging/windows/portable.cmake
# Assembles a portable Windows distribution into a staging directory.
#
# Usage:
#   cmake -DSTAGE_DIR=<output> -DBUILD_DIR=<build> -DSOURCE_DIR=<source> -P portable.cmake
#
# Produces:
#   <STAGE_DIR>/
#     gamemodmanager.exe
#     plugins/             (*.dll files from build/plugins/)
#     instance.toml        (template)
#     config/              (empty, ready for first launch)

cmake_minimum_required(VERSION 3.20)

if(NOT STAGE_DIR)
    message(FATAL_ERROR "STAGE_DIR not set — pass -DSTAGE_DIR=<path>")
endif()
if(NOT BUILD_DIR)
    message(FATAL_ERROR "BUILD_DIR not set — pass -DBUILD_DIR=<path>")
endif()
if(NOT SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR not set — pass -DSOURCE_DIR=<path>")
endif()

file(MAKE_DIRECTORY "${STAGE_DIR}")
file(MAKE_DIRECTORY "${STAGE_DIR}/plugins")
file(MAKE_DIRECTORY "${STAGE_DIR}/config")
file(MAKE_DIRECTORY "${STAGE_DIR}/mods")
file(MAKE_DIRECTORY "${STAGE_DIR}/downloads")
file(MAKE_DIRECTORY "${STAGE_DIR}/cache")
file(MAKE_DIRECTORY "${STAGE_DIR}/logs")

# Copy the built executable
file(COPY "${BUILD_DIR}/gamemodmanager.exe"
     DESTINATION "${STAGE_DIR}")

# Copy plugin DLLs
file(GLOB PLUGIN_FILES "${BUILD_DIR}/plugins/*.dll")
if(PLUGIN_FILES)
    file(COPY ${PLUGIN_FILES} DESTINATION "${STAGE_DIR}/plugins")
endif()

# Copy Qt DLLs from the build directory (windeployqt output)
# Run windeployqt after build: windeployqt --no-translations gamemodmanager.exe
file(GLOB QT_DLLS "${BUILD_DIR}/*.dll")
if(QT_DLLS)
    file(COPY ${QT_DLLS} DESTINATION "${STAGE_DIR}")
endif()

# Copy VC++ redistributable if present
file(GLOB VC_REDIST "${BUILD_DIR}/vc_redist.*.dll")
if(VC_REDIST)
    file(COPY ${VC_REDIST} DESTINATION "${STAGE_DIR}")
endif()

# Template instance.toml
file(WRITE "${STAGE_DIR}/instance.toml"
"# Generated by GameModManager portable packaging\n"
"game_id = \"\"\n"
"game_name = \"\"\n"
"created = \"\"\n"
)

message(STATUS "Portable staging complete: ${STAGE_DIR}")
