#include "engine/core/instance/instance_snapshot.h"

#include "engine/core/instance/toml_utils.h"
#include "engine/deploy/deploy_utils.h"
#include "engine/profile/safe_write_file.h"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <toml++/toml.hpp>
#include <unordered_set>

namespace engine {

namespace {

  // Persistent deploy ledger filename at the instance root (direct-symlink
  // mode). See deploy_all_enabled_mods_direct docs in deploy_utils.h.
  constexpr const char *kDeployLedgerFileName = ".gmm_deploy_ledger";

  // ---------------------------------------------------------------------------
  // File I/O helpers
  // ---------------------------------------------------------------------------

  std::string read_file_text(const std::filesystem::path &p) {
    std::ifstream in(p, std::ios::binary);
    if (!in)
      return {};
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
  }

  bool write_file_atomic(const std::filesystem::path &p, const std::string &content) {
    return profile::safe_write_file(p, content);
  }

  std::string trim(const std::string &s) {
    auto b = s.find_first_not_of(" \t\r\n");
    if (b == std::string::npos)
      return {};
    auto e = s.find_last_not_of(" \t\r\n");
    return s.substr(b, e - b + 1);
  }

  // ---------------------------------------------------------------------------
  // modlist.txt helpers
  // ---------------------------------------------------------------------------

  // Parse modlist.txt into priority-ascending ModListEntry vector.
  // File format: first line = highest priority. '+A' enabled, '-A' disabled,
  // '*A' foreign, bare 'A' = enabled. Comments ('#') and blanks skipped.
  std::vector<profile::ModListEntry> parse_modlist(const std::string &content) {
    std::vector<profile::ModListEntry> entries;
    std::unordered_set<std::string> seen;
    std::istringstream stream(content);
    std::string line;
    while (std::getline(stream, line)) {
      if (!line.empty() && line.back() == '\r')
        line.pop_back();
      const auto t = trim(line);
      if (t.empty() || t[0] == '#')
        continue;
      bool enabled = true;
      bool foreign = false;
      std::string mod_id;
      switch (t[0]) {
      case '-':
        enabled = false;
        mod_id  = trim(t.substr(1));
        break;
      case '*':
        foreign = true;
        mod_id  = trim(t.substr(1));
        break;
      case '+':
        mod_id = trim(t.substr(1));
        break;
      default:
        mod_id = t;
        break;
      }
      if (mod_id.empty())
        continue;
      if (!seen.insert(mod_id).second)
        continue;
      entries.push_back({mod_id, enabled, foreign, 0});
    }
    // File order: first line = highest priority.
    // Convert to priority-ascending: index 0 = lowest priority.
    // Invert so first line gets highest priority value.
    const int n = static_cast<int>(entries.size());
    for (int i = 0; i < n; ++i)
      entries[i].priority = n - 1 - i;
    return entries;
  }

  // Serialize priority-ascending ModListEntry vector to modlist.txt content.
  std::string serialize_modlist(const std::vector<profile::ModListEntry> &mods) {
    std::string content =
        "# This file was automatically generated by GameModManager.\r\n";
    // Write in reverse priority order: highest priority first (MO2 convention).
    for (auto it = mods.rbegin(); it != mods.rend(); ++it) {
      content += it->foreign ? '*' : (it->enabled ? '+' : '-');
      content += it->mod_id;
      content += "\r\n";
    }
    return content;
  }

  // ---------------------------------------------------------------------------
  // Line-based file helpers (plugins.txt, loadorder.txt, archives.txt)
  // ---------------------------------------------------------------------------

  std::vector<std::string> read_lines(const std::filesystem::path &path) {
    std::vector<std::string> lines;
    const auto content = read_file_text(path);
    if (content.empty())
      return lines;
    std::istringstream stream(content);
    std::string line;
    while (std::getline(stream, line)) {
      if (!line.empty() && line.back() == '\r')
        line.pop_back();
      const auto t = trim(line);
      if (!t.empty())
        lines.push_back(t);
    }
    return lines;
  }

  bool write_lines(const std::filesystem::path &path,
                   const std::vector<std::string> &lines) {
    std::string content;
    for (const auto &line : lines) {
      content += line;
      content += '\n';
    }
    return write_file_atomic(path, content);
  }

  // ---------------------------------------------------------------------------
  // lockedorder.txt helpers
  // ---------------------------------------------------------------------------

  std::vector<profile::LockedPlugin>
  read_locked_order(const std::filesystem::path &path) {
    std::vector<profile::LockedPlugin> result;
    for (const auto &line : read_lines(path)) {
      const auto sep = line.find('|');
      if (sep == std::string::npos)
        continue;
      const auto name = trim(line.substr(0, sep));
      if (name.empty())
        continue;
      int priority  = 0;
      auto prio_str = trim(line.substr(sep + 1));
      if (prio_str.empty())
        continue;
      try {
        priority = std::stoi(prio_str);
      } catch (...) {
        continue;
      }
      result.push_back({name, priority});
    }
    return result;
  }

  bool write_locked_order(const std::filesystem::path &path,
                          const std::vector<profile::LockedPlugin> &locked) {
    std::string content;
    for (const auto &e : locked) {
      content += e.name + "|" + std::to_string(e.priority) + "\n";
    }
    return write_file_atomic(path, content);
  }

  // ---------------------------------------------------------------------------
  // settings.ini helpers
  // ---------------------------------------------------------------------------

  // Minimal settings.ini: root-section keys only.
  struct ProfileSettings {
    bool local_saves               = false;
    bool local_settings            = false;
    bool auto_archive_invalidation = false;
  };

  ProfileSettings parse_settings_ini(const std::string &content) {
    ProfileSettings s;
    std::istringstream stream(content);
    std::string line;
    while (std::getline(stream, line)) {
      if (!line.empty() && line.back() == '\r')
        line.pop_back();
      auto t = trim(line);
      if (t.empty() || t[0] == ';' || t[0] == '#' || t[0] == '[')
        continue;
      auto sep = t.find('=');
      if (sep == std::string::npos)
        continue;
      auto key = trim(t.substr(0, sep));
      auto val = trim(t.substr(sep + 1));
      if (key == "LocalSaves")
        s.local_saves = (val == "true" || val == "1");
      else if (key == "LocalSettings")
        s.local_settings = (val == "true" || val == "1");
      else if (key == "AutomaticArchiveInvalidation")
        s.auto_archive_invalidation = (val == "true" || val == "1");
    }
    return s;
  }

  std::string serialize_settings_ini(const ProfileSettings &s) {
    std::string out;
    out += "LocalSaves=";
    out += s.local_saves ? "true" : "false";
    out += '\n';
    out += "LocalSettings=";
    out += s.local_settings ? "true" : "false";
    out += '\n';
    out += "AutomaticArchiveInvalidation=";
    out += s.auto_archive_invalidation ? "true" : "false";
    out += '\n';
    return out;
  }

  // ---------------------------------------------------------------------------
  // TOML executables helpers
  // ---------------------------------------------------------------------------

  std::vector<ExecutableEntry> parse_executables_from_toml(const toml::table &tbl) {
    std::vector<ExecutableEntry> result;
    auto arr = tbl["executables"].as_array();
    if (!arr)
      return result;
    result.reserve(arr->size());
    for (const auto &elem : *arr) {
      auto t = elem.as_table();
      if (!t)
        continue;
      ExecutableEntry e;
      if (auto v = (*t)["path"].value<std::string>())
        e.path = *v;
      if (auto v = (*t)["title"].value<std::string>())
        e.title = *v;
      if (auto v = (*t)["args"].value<std::string>())
        e.args = *v;
      if (auto v = (*t)["cwd"].value<std::string>())
        e.cwd = *v;
      if (auto v = (*t)["mod"].value<std::string>())
        e.mod = *v;
      if (auto v = (*t)["icon"].value<std::string>())
        e.icon = *v;
      if (auto *env_arr = (*t)["env"].as_array()) {
        for (const auto &v : *env_arr) {
          if (auto s = v.value<std::string>())
            e.env.push_back(*s);
        }
      }
      result.push_back(std::move(e));
    }
    return result;
  }

  toml::array executables_to_toml(const std::vector<ExecutableEntry> &execs) {
    toml::array arr;
    for (const auto &e : execs) {
      toml::table t;
      if (!e.path.empty())
        t.emplace("path", e.path);
      if (!e.title.empty())
        t.emplace("title", e.title);
      if (!e.args.empty())
        t.emplace("args", e.args);
      if (!e.cwd.empty())
        t.emplace("cwd", e.cwd);
      if (!e.mod.empty())
        t.emplace("mod", e.mod);
      if (!e.icon.empty())
        t.emplace("icon", e.icon);
      if (!e.env.empty()) {
        toml::array env_arr;
        for (const auto &v : e.env)
          env_arr.push_back(v);
        t.emplace("env", std::move(env_arr));
      }
      // Non-inline so the formatter emits [[executables]] sections (the
      // on-disk convention), not a single inline `executables = [...]` line.
      arr.push_back(std::move(t));
    }
    return arr;
  }

}  // namespace

// ---------------------------------------------------------------------------
// InstanceSnapshot::capture
// ---------------------------------------------------------------------------

InstanceSnapshot InstanceSnapshot::capture(const Instance &instance) {
  InstanceSnapshot snap;
  // Refresh config from disk: from_root() does not read instance.toml, so
  // the in-memory info may be empty/stale. A missing/unparseable file keeps
  // the in-memory values.
  Instance inst = instance;
  inst.read_toml();
  const auto &info = inst.info();

  // Instance config.
  snap.game_id          = info.game_id;
  snap.display_name     = info.display_name;
  snap.portable         = info.portable;
  snap.deploy_strategy  = info.deploy_strategy;
  snap.modpack_id       = info.modpack_id;
  snap.modpack_revision = info.modpack_revision;
  snap.proton_runner    = info.proton_runner;
  snap.steam_appid      = info.steam_appid;

  // Mod tracking entries.
  ModStateTracker tracker(info.root);
  tracker.load();
  snap.mod_entries        = tracker.all_entries();
  snap.next_install_order = tracker.next_install_order();

  // Profiles.
  auto profiles_dir = instance.path_for(InstanceKind::Profiles);
  if (std::filesystem::exists(profiles_dir)) {
    for (const auto &entry : std::filesystem::directory_iterator(profiles_dir)) {
      if (!entry.is_directory())
        continue;
      ProfileSnapshot ps;
      ps.name = entry.path().filename().string();

      // modlist.txt
      ps.mods = parse_modlist(read_file_text(entry.path() / "modlist.txt"));

      // plugins.txt
      ps.plugins = read_lines(entry.path() / "plugins.txt");

      // loadorder.txt
      ps.load_order = read_lines(entry.path() / "loadorder.txt");

      // lockedorder.txt
      ps.locked_order = read_locked_order(entry.path() / "lockedorder.txt");

      // archives.txt
      ps.archives = read_lines(entry.path() / "archives.txt");

      // settings.ini
      auto settings = parse_settings_ini(read_file_text(entry.path() / "settings.ini"));
      ps.local_saves               = settings.local_saves;
      ps.local_settings            = settings.local_settings;
      ps.auto_archive_invalidation = settings.auto_archive_invalidation;

      // initweaks.ini
      ps.tweaked_ini = read_file_text(entry.path() / "initweaks.ini");

      snap.profiles.push_back(std::move(ps));
    }
  }

  // Executables from instance.toml.
  auto tbl = parse_instance_toml(instance.toml_path());
  if (tbl)
    snap.executables = parse_executables_from_toml(*tbl);

  // Deployed file manifest (<instance>/.gmm_deploy_ledger TSV).
  for (const auto &[target, source] :
       load_deploy_ledger(info.root / kDeployLedgerFileName)) {
    snap.deployed_files.push_back({target.string(), source.string()});
  }

  return snap;
}

// ---------------------------------------------------------------------------
// InstanceSnapshot::apply
// ---------------------------------------------------------------------------

bool InstanceSnapshot::apply(const Instance &instance) const {
  const auto &root = instance.info().root;

  // 1. Write instance.toml (config + executables).
  // Read-modify-write: machine-local keys the snapshot does not own
  // (game_dir, per-folder overrides, plugins_txt_path, last_tab, ...) must
  // survive a restore. A missing/unparseable file starts from empty.
  toml::table tbl;
  if (auto existing = parse_instance_toml(instance.toml_path()))
    tbl = std::move(*existing);
  tbl.insert_or_assign("game_id", game_id);
  tbl.insert_or_assign("name", display_name);
  tbl.insert_or_assign("portable", portable);
  if (steam_appid > 0)
    tbl.insert_or_assign("steam_appid", static_cast<int64_t>(steam_appid));
  else
    tbl.erase("steam_appid");
  if (!deploy_strategy.empty())
    tbl.insert_or_assign("deploy_strategy", deploy_strategy);
  else
    tbl.erase("deploy_strategy");
  if (!modpack_id.empty())
    tbl.insert_or_assign("modpack_id", modpack_id);
  else
    tbl.erase("modpack_id");
  if (modpack_revision > 0)
    tbl.insert_or_assign("modpack_revision", modpack_revision);
  else
    tbl.erase("modpack_revision");
  if (!proton_runner.empty())
    tbl.insert_or_assign("proton_runner", proton_runner);
  else
    tbl.erase("proton_runner");
  if (!executables.empty())
    tbl.insert_or_assign("executables", executables_to_toml(executables));
  else
    tbl.erase("executables");

  {
    std::ofstream out(instance.toml_path());
    if (!out)
      return false;
    out << serialize_instance_toml(tbl);
    if (!out.good())
      return false;
  }
  invalidate_instance_toml_cache(instance.toml_path());

  // 2. Write mod_state.json.
  ModStateTracker tracker(root);
  tracker.set_all_entries(mod_entries);
  if (!tracker.save())
    return false;

  // 3. Write profile directories.
  auto profiles_dir = instance.path_for(InstanceKind::Profiles);
  std::error_code ec;
  std::filesystem::create_directories(profiles_dir, ec);
  if (ec)
    return false;

  for (const auto &ps : profiles) {
    auto dir = profiles_dir / ps.name;
    std::filesystem::create_directories(dir, ec);
    if (ec)
      return false;

    // modlist.txt
    if (!write_file_atomic(dir / "modlist.txt", serialize_modlist(ps.mods)))
      return false;

    // plugins.txt
    if (!write_lines(dir / "plugins.txt", ps.plugins))
      return false;

    // loadorder.txt
    if (!write_lines(dir / "loadorder.txt", ps.load_order))
      return false;

    // lockedorder.txt
    if (!write_locked_order(dir / "lockedorder.txt", ps.locked_order))
      return false;

    // archives.txt
    if (!write_lines(dir / "archives.txt", ps.archives))
      return false;

    // settings.ini
    ProfileSettings settings;
    settings.local_saves               = ps.local_saves;
    settings.local_settings            = ps.local_settings;
    settings.auto_archive_invalidation = ps.auto_archive_invalidation;
    if (!write_file_atomic(dir / "settings.ini", serialize_settings_ini(settings)))
      return false;

    // initweaks.ini (only when non-empty, matching ProfileManager behavior)
    if (!ps.tweaked_ini.empty()) {
      if (!write_file_atomic(dir / "initweaks.ini", ps.tweaked_ini))
        return false;
    }
  }

  // 4. Write the deployed file manifest (same TSV format the deploy
  // executor persists). An empty snapshot manifest removes a stale ledger
  // so apply -> capture round-trips exactly.
  {
    auto ledger_path = root / kDeployLedgerFileName;
    if (deployed_files.empty()) {
      std::error_code ec;
      std::filesystem::remove(ledger_path, ec);
    } else {
      std::string content;
      for (const auto &d : deployed_files) {
        content += d.target;
        content += '\t';
        content += d.source;
        content += '\n';
      }
      if (!write_file_atomic(ledger_path, content))
        return false;
    }
  }

  return true;
}

// ---------------------------------------------------------------------------
// InstanceSnapshot::to_json
// ---------------------------------------------------------------------------

nlohmann::json InstanceSnapshot::to_json() const {
  nlohmann::json j;
  j["version"]      = 1;
  j["game_id"]      = game_id;
  j["display_name"] = display_name;
  j["portable"]     = portable;
  if (!deploy_strategy.empty())
    j["deploy_strategy"] = deploy_strategy;
  if (!modpack_id.empty())
    j["modpack_id"] = modpack_id;
  if (modpack_revision > 0)
    j["modpack_revision"] = modpack_revision;
  if (!proton_runner.empty())
    j["proton_runner"] = proton_runner;
  if (steam_appid > 0)
    j["steam_appid"] = steam_appid;

  // Mod entries (reuse ModTrackingEntry JSON format from mod_state.json).
  nlohmann::json entries_obj;
  for (const auto &[key, e] : mod_entries) {
    nlohmann::json val;
    val["install_order"] = e.install_order;
    val["installed_at"]  = e.installed_at;
    val["list_position"] = e.list_position;
    if (!e.parent_separator.empty())
      val["parent_separator"] = e.parent_separator;
    val["depth"] = e.depth;
    if (!e.separator_color.empty())
      val["separator_color"] = e.separator_color;
    if (e.collapsed)
      val["collapsed"] = true;
    if (e.hidden)
      val["hidden"] = true;
    if (e.disabled)
      val["disabled"] = true;
    if (!e.hidden_files.empty())
      val["hidden_files"] = e.hidden_files;
    if (e.deploy_at_root)
      val["deploy_at_root"] = true;
    entries_obj[key] = std::move(val);
  }
  j["mod_entries"]        = std::move(entries_obj);
  j["next_install_order"] = next_install_order;

  // Profiles.
  nlohmann::json profiles_arr = nlohmann::json::array();
  for (const auto &ps : profiles) {
    nlohmann::json pj;
    pj["name"] = ps.name;
    // Modlist (compact: just mod_id/enabled/foreign).
    nlohmann::json mods_arr = nlohmann::json::array();
    for (const auto &m : ps.mods) {
      nlohmann::json mj;
      mj["mod_id"]  = m.mod_id;
      mj["enabled"] = m.enabled;
      if (m.foreign)
        mj["foreign"] = true;
      mj["priority"] = m.priority;
      mods_arr.push_back(std::move(mj));
    }
    pj["mods"]       = std::move(mods_arr);
    pj["plugins"]    = ps.plugins;
    pj["load_order"] = ps.load_order;
    // Locked order.
    nlohmann::json locked_arr = nlohmann::json::array();
    for (const auto &lo : ps.locked_order) {
      nlohmann::json loj;
      loj["name"]     = lo.name;
      loj["priority"] = lo.priority;
      locked_arr.push_back(std::move(loj));
    }
    pj["locked_order"]              = std::move(locked_arr);
    pj["archives"]                  = ps.archives;
    pj["local_saves"]               = ps.local_saves;
    pj["local_settings"]            = ps.local_settings;
    pj["auto_archive_invalidation"] = ps.auto_archive_invalidation;
    if (!ps.tweaked_ini.empty())
      pj["tweaked_ini"] = ps.tweaked_ini;
    profiles_arr.push_back(std::move(pj));
  }
  j["profiles"] = std::move(profiles_arr);

  // Executables.
  nlohmann::json exec_arr = nlohmann::json::array();
  for (const auto &e : executables) {
    nlohmann::json ej;
    ej["path"] = e.path;
    if (!e.title.empty())
      ej["title"] = e.title;
    if (!e.args.empty())
      ej["args"] = e.args;
    if (!e.cwd.empty())
      ej["cwd"] = e.cwd;
    if (!e.mod.empty())
      ej["mod"] = e.mod;
    if (!e.icon.empty())
      ej["icon"] = e.icon;
    if (!e.env.empty())
      ej["env"] = e.env;
    exec_arr.push_back(std::move(ej));
  }
  j["executables"] = std::move(exec_arr);

  // Deployed file manifest.
  nlohmann::json deployed_arr = nlohmann::json::array();
  for (const auto &d : deployed_files) {
    nlohmann::json dj;
    dj["target"] = d.target;
    dj["source"] = d.source;
    deployed_arr.push_back(std::move(dj));
  }
  j["deployed_files"] = std::move(deployed_arr);

  return j;
}

// ---------------------------------------------------------------------------
// InstanceSnapshot::from_json
// ---------------------------------------------------------------------------

InstanceSnapshot InstanceSnapshot::from_json(const nlohmann::json &j) {
  InstanceSnapshot snap;
  if (!j.is_object())
    return snap;

  snap.game_id          = j.value("game_id", "");
  snap.display_name     = j.value("display_name", "");
  snap.portable         = j.value("portable", true);
  snap.deploy_strategy  = j.value("deploy_strategy", "");
  snap.modpack_id       = j.value("modpack_id", "");
  snap.modpack_revision = j.value("modpack_revision", int64_t(0));
  snap.proton_runner    = j.value("proton_runner", "");
  snap.steam_appid      = j.value("steam_appid", 0u);

  // Mod entries.
  if (auto it = j.find("mod_entries"); it != j.end() && it->is_object()) {
    for (auto &[key, val] : it->items()) {
      if (!val.is_object())
        continue;
      ModTrackingEntry e;
      e.install_order    = val.value("install_order", 0u);
      e.installed_at     = val.value("installed_at", int64_t(0));
      e.list_position    = val.value("list_position", -1);
      e.parent_separator = val.value("parent_separator", std::string());
      e.depth            = val.value("depth", 0);
      e.separator_color  = val.value("separator_color", std::string());
      e.collapsed        = val.value("collapsed", false);
      e.hidden           = val.value("hidden", false);
      e.disabled         = val.value("disabled", false);
      e.deploy_at_root   = val.value("deploy_at_root", false);
      if (auto hf = val.find("hidden_files"); hf != val.end() && hf->is_array()) {
        e.hidden_files = hf->get<std::vector<std::string>>();
      }
      snap.mod_entries[key] = std::move(e);
    }
  }
  snap.next_install_order = j.value("next_install_order", 0u);

  // Profiles.
  if (auto it = j.find("profiles"); it != j.end() && it->is_array()) {
    for (const auto &pj : *it) {
      ProfileSnapshot ps;
      ps.name = pj.value("name", "");
      if (auto mi = pj.find("mods"); mi != pj.end() && mi->is_array()) {
        for (const auto &mj : *mi) {
          profile::ModListEntry m;
          m.mod_id   = mj.value("mod_id", "");
          m.enabled  = mj.value("enabled", true);
          m.foreign  = mj.value("foreign", false);
          m.priority = mj.value("priority", 0);
          ps.mods.push_back(std::move(m));
        }
      }
      if (auto v = pj.find("plugins"); v != pj.end() && v->is_array())
        ps.plugins = v->get<std::vector<std::string>>();
      if (auto v = pj.find("load_order"); v != pj.end() && v->is_array())
        ps.load_order = v->get<std::vector<std::string>>();
      if (auto lo = pj.find("locked_order"); lo != pj.end() && lo->is_array()) {
        for (const auto &loj : *lo) {
          profile::LockedPlugin lp;
          lp.name     = loj.value("name", "");
          lp.priority = loj.value("priority", 0);
          ps.locked_order.push_back(std::move(lp));
        }
      }
      if (auto v = pj.find("archives"); v != pj.end() && v->is_array())
        ps.archives = v->get<std::vector<std::string>>();
      ps.local_saves               = pj.value("local_saves", false);
      ps.local_settings            = pj.value("local_settings", false);
      ps.auto_archive_invalidation = pj.value("auto_archive_invalidation", false);
      ps.tweaked_ini               = pj.value("tweaked_ini", "");
      snap.profiles.push_back(std::move(ps));
    }
  }

  // Executables.
  if (auto it = j.find("executables"); it != j.end() && it->is_array()) {
    for (const auto &ej : *it) {
      ExecutableEntry e;
      e.path  = ej.value("path", "");
      e.title = ej.value("title", "");
      e.args  = ej.value("args", "");
      e.cwd   = ej.value("cwd", "");
      e.mod   = ej.value("mod", "");
      e.icon  = ej.value("icon", "");
      if (auto v = ej.find("env"); v != ej.end() && v->is_array())
        e.env = v->get<std::vector<std::string>>();
      snap.executables.push_back(std::move(e));
    }
  }

  // Deployed file manifest.
  if (auto it = j.find("deployed_files"); it != j.end() && it->is_array()) {
    for (const auto &dj : *it) {
      DeployedFile d;
      d.target = dj.value("target", "");
      d.source = dj.value("source", "");
      if (!d.target.empty())
        snap.deployed_files.push_back(std::move(d));
    }
  }

  return snap;
}

// ---------------------------------------------------------------------------
// InstanceSnapshot::save / load
// ---------------------------------------------------------------------------

bool InstanceSnapshot::save(const std::filesystem::path &path) const {
  auto j   = to_json();
  auto tmp = path;
  tmp += ".tmp";
  std::ofstream out(tmp);
  if (!out)
    return false;
  out << j.dump(2) << "\n";
  if (!out.good()) {
    std::error_code ec;
    std::filesystem::remove(tmp, ec);
    return false;
  }
  out.close();
  std::error_code ec;
  std::filesystem::rename(tmp, path, ec);
  return !ec;
}

InstanceSnapshot InstanceSnapshot::load(const std::filesystem::path &path) {
  std::ifstream in(path);
  if (!in)
    return {};
  nlohmann::json j;
  try {
    j = nlohmann::json::parse(in);
  } catch (const nlohmann::json::parse_error &) {
    return {};
  }
  return from_json(j);
}

}  // namespace engine
